models:
  - type: main
    engine: azure
    model: gpt-4o
    api_key: ${AZURE_API_KEY}
    api_base: https://voicelive1-resource.cognitiveservices.azure.com/
    api_version: 2024-12-01-preview
    deployment_name: gpt-4o


rails:
  input:
    parallel: true
    flows: []
      # - content_safety_check_input
      # - topic_safety_check_input

  dialog:
    flows:
      - route_by_role
      - enforce_rag_flow

  output:
    parallel: true
    flows:
      - content_safety_check_output
      - self_check_output
      - enforce_refusal_policy

    streaming:
      enabled: true
      chunk_size: 200
      context_size: 50
      stream_first: true

streaming: true
